version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=your_project.settings
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: on-failure
    volumes:
      - "db0:/var/lib/postgresql/selectioncourse"
    environment:
      - POSTGRES_USER=selectioncourse
      - POSTGRES_PASSWORD=selecti0nc0urse
    ports:
      - "5353:5432"
    networks:
      - selectioncourse
  server:
    build: .
    restart: on-failure
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG_MODE=true
    ports:
      - "8080:8000"
    depends_on:
      - db
    expose:
      - "8000"
    networks:
      - selectioncourse
  minio:
    image: minio/minio
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=your_access_key
      - MINIO_SECRET_KEY=your_secret_key
    command: server /data

volumes:
  db0:
    driver: local

networks:
  selectioncourse:
    driver: bridge
